### ISSUE TITLE
Limit providers based on settings

### ISSUE THREAD

**Issue by johnhidey** [tigerxy/VSCode-ShareCode#12]
Limit the share code providers that are shown when doing a `CTRL + ALT + P` and selecting either open or share.  

So if no settings are provided for say gitlab, then the gitlab option would not be one that could be chosen.

Loving the extension, keep'em coming.

**Comment by tigerxy** [comment]
Would it help if the unconfigured options appear as last in the list?

**Comment by johnhidey** [comment]
That might work also.  Just threw out the idea.  I wasn't having any problems with it.  It works great.
